export const pricingTiers = [
    {
        name: "BASIS",
        price: 149,
        recommended: false,
        badge: "Beste prijs/kwaliteit",
        color: "green",
        roi: "Terugverdiend in 3-6 maanden",
        features: [
            "24/7 Temperatuurregistratie (±0.5°C)",
            "Live Google Sheets dashboard",
            "HACCP & GDP compliant logging",
            "Soldeervrije installatie (5 min)",
            "Bespaar €520/jaar op administratie",
            "1 jaar garantie + email support",
        ],
        idealFor: "Keukenkoelkasten en algemene opslag",
        ctaText: "Start met BASIS",
    },
    {
        name: "PRO",
        price: 199,
        recommended: true,
        badge: "Populairste keuze",
        color: "yellow",
        roi: "Terugverdiend na 1e prevented incident",
        features: [
            "Alles van BASIS +",
            "Deurdetectie (>60 sec open = alarm)",
            "Lokaal geluidssignaal (zoemer)",
            "Email alerts bij temperatuuroverschrijding",
            "Voorkomt medicatiebatch verlies (€500-€2.000)",
            "Energiebesparing door deurmonitoring",
        ],
        idealFor: "Medicatiekoelkasten in zorg en apotheken",
        ctaText: "Vraag Gratis Proefinstallatie",
        popularityLabel: "65% van klanten kiest PRO",
    },
    {
        name: "ELITE",
        price: 249,
        recommended: false,
        badge: "Maximale bescherming",
        color: "red",
        roi: "Beschermt €5.000-€50.000+ voorraad",
        features: [
            "Alles van PRO +",
            "Luchtvochtigheid & luchtdruk monitoring",
            "Batterij backup bij stroomuitval",
            "Black Box functionaliteit (3-6 mnd autonomie)",
            "IGJ/GGD audit-ready compliance",
            "Power-loss detection met noodmelding",
        ],
        idealFor: "Vaccinopslag en kritieke medicatie (GGD, ziekenhuizen)",
        ctaText: "Plan Persoonlijk Adviesgesprek",
    },
] as const;
